# This GitHub Actions workflow deploys your Next.js app to Firebase App Hosting.
#
# To get started:
# 1. Replace <YOUR_FIREBASE_PROJECT_ID> and <YOUR_APP_HOSTING_SITE_ID> with your actual project values.
#    You can find these in your Firebase project settings and the App Hosting page in the Firebase console.
# 2. Create the following secrets in your GitHub repository settings (Settings > Secrets and variables > Actions):
#    - FIREBASE_SERVICE_ACCOUNT_JSON: The JSON content of a service account key with the "Firebase App Hosting Admin" role.
#      To get this:
#      a. Go to your Firebase project settings -> Service accounts.
#      b. Generate a new private key and download the JSON file.
#      c. Copy the entire content of the file into this secret.
#    - NEXT_PUBLIC_SUPABASE_URL: Your Supabase project URL.
#    - NEXT_PUBLIC_SUPABASE_ANON_KEY: Your Supabase anonymous (public) key.
#
# For more information, see: https://firebase.google.com/docs/app-hosting/ci-cd

name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # Required for authentication with Google Cloud

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase App Hosting
        uses: firebase-actions/setup-app-hosting@main
        with:
          # Your Firebase project ID.
          project_id: <YOUR_FIREBASE_PROJECT_ID>
          # The ID of your App Hosting site. Find this in the Firebase console.
          site_id: <YOUR_APP_HOSTING_SITE_ID>
          # The service account key JSON stored as a GitHub secret.
          service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          # Environment variables required for the build step.
          env: |
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
